version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gogarid/devops-for-programmers-project-74:latest
    command: bash -c 'sleep 5 && npm test'
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

