name: Build and Push

on:
  push:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build App
      run: |
        docker-compose run --rm app npm ci
        docker-compose run --rm app npm test
        docker buildx build --platform linux/amd64,linux/arm64 -t gogarid/devops-for-programmers-project-74:latest .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push gogarid/devops-for-programmers-project-74:latest

    - name: Check
      run: |
        make compose-test 